networks:
  proxy:
    name: "proxy"

services:
  traefik:
    image: traefik:v2.3
    container_name: traefik
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock